Create comments
AndreyMukhametzyanov/CoursesApp pull request #19
Opened 2022-03-31 10:36 UTC by AndreyMukhametzyanov

2022-04-04 17:05 UTC, GolovkoStepan commented on app/views/comments/_comments.html.erb
> +<% resource.comments.each do |c| %>
resource.comments.includes(:user).each

2022-04-05 06:50 UTC, AndreyMukhametzyanov commented on app/views/comments/_comments.html.erb
> +<% resource.comments.each do |c| %>
Понял. Слушай я думал что все же это надо в контроллере делать))) Не зря попросил тебя прокомментить

2022-04-05 06:50 UTC, AndreyMukhametzyanov commented on app/views/comments/_comments.html.erb
> +<% resource.comments.each do |c| %>
Исправил

2022-04-05 13:17 UTC, GolovkoStepan commented on app/controllers/comments_controller.rb
> +    comment.save ? flash[:notice] = I18n.t('comments.create.success') : flash[:alert] = I18n.t('comments.create.error')
```suggestion
    flash[:notice] =  comment.save ? I18n.t('comments.create.success') : I18n.t('comments.create.error')
```

2022-04-05 13:20 UTC, GolovkoStepan commented on app/views/comments/_form.html.erb
> +  <%= f.input :body, input_html: { style: "width: 641px" } %>
такой инлайн css нежелателен, лучше юзать bootstrap классы или писать свои. Такое захардкоженое ограничение ширины будет не адаптивно на разных дисплеях. Пока можно не исправлять

2022-04-05 13:20 UTC, GolovkoStepan commented on app/views/comments/_comments.html.erb
> +      <!--      <a href="#" class="btn btn-primary">Go somewhere</a>-->
если это не нужно - можно удалить, чтобы мусора не было

2022-04-05 13:23 UTC, GolovkoStepan commented on spec/controllers/comments_controller_spec.rb
> +      let(:one_comment) { course.lessons.last.comments.last }
```suggestion
      let(:one_comment) { lesson.comments.last }
```

2022-04-05 13:26 UTC, GolovkoStepan requested changes
Все хорошо, только сообщение об ошибке не информативно. Добавь ошибку из errors в флеш, чтобы было понятно что именно не так

2022-04-05 13:35 UTC, AndreyMukhametzyanov commented on app/controllers/comments_controller.rb
> +    comment.save ? flash[:notice] = I18n.t('comments.create.success') : flash[:alert] = I18n.t('comments.create.error')
ну так мы же не сможем отобразить алерт при ошибке если так рефакторить

2022-04-05 13:37 UTC, AndreyMukhametzyanov commented on app/views/comments/_form.html.erb
> +  <%= f.input :body, input_html: { style: "width: 641px" } %>
я так понимаю что надо будет оборачивать инпут в какой то див и вешать класс?

2022-04-05 13:39 UTC, AndreyMukhametzyanov commented on spec/controllers/comments_controller_spec.rb
> +      let(:comments) { course.lessons.last.comments }
Исправил

2022-04-05 13:40 UTC, AndreyMukhametzyanov commented on app/views/comments/_comments.html.erb
> +        <div class="col-sm-4" style="padding-left: 30px;padding-right: 0px;">
ок

2022-04-05 19:26 UTC, GolovkoStepan approved these changes

2022-04-05 19:26 UTC, merged