Active_storage
AndreyMukhametzyanov/CoursesApp pull request #25
Opened 2022-04-14 13:54 UTC by AndreyMukhametzyanov

2022-04-15 14:12 UTC, GolovkoStepan commented on app/models/course.rb
> +    if cover_picture.content_type.in?(image_types)
```suggestion
errors.add(:cover_picture, :is_not_picture_type) unless cover_picture.content_type.in?(image_types)
```

2022-04-16 12:32 UTC, AndreyMukhametzyanov commented on app/views/courses/_form.html.erb
> +  <%= f.input :cover_picture, as: :file, class: "my-3" %>
добавил

2022-04-18 17:59 UTC, GolovkoStepan commented on spec/models/lesson_spec.rb
> +    let(:user) { build(:user) }
можно не создавать пользователя отдельно, а создать просто курс. Пользователь создастся вместе с ним

2022-04-18 18:00 UTC, GolovkoStepan commented on spec/models/lesson_spec.rb
> +      expect(lesson).to be_owner(user)
и уже потом использовать вот так
```suggestion
      expect(lesson).to be_owner(course.author)
```

2022-04-18 18:01 UTC, GolovkoStepan commented on spec/models/course_spec.rb
> +      let(:file) { Rack::Test::UploadedFile.new(Rails.root.join('spec/fixtures/files/test.txt')) }
создание файлов есть в обоих контекстах, вынеси его на уровень выше, чтобы не дублировать

2022-04-18 18:07 UTC, GolovkoStepan commented on spec/controllers/attachments_controller_spec.rb
> +RSpec.describe AttachmentsController, type: :controller do
тут много дублирования, некоторые let используются и там, и тут. Вынеси общие let выше на уровень, чтобы не писать одно и тоже 

например,  let!(:course) { create :course, author: user } и так далее

2022-04-18 18:09 UTC, GolovkoStepan commented on app/models/course.rb
> +    image_types = %w[image/gif image/jpeg image/pjpeg image/png image/svg+xml
давай это унесем в константы и сделаем глобальной константой для всех моделей.

2022-04-18 18:12 UTC, GolovkoStepan commented on app/controllers/attachments_controller.rb
> +  def redirect_with_alert(path, msg)
эти методы (redirect_with_alert redirect_with_notice redirect_by_kind) ты уже использовал где-то, давай их вынесем в родительский класс
нужно будет удалить методы-дубликаты и использовать эти

2022-04-18 18:13 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
>    def redirect_with_alert
вот этот метод, еще есть аналогичны redirect_to_promo_with_alert

2022-04-18 18:13 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
>    def redirect_with_alert
и тут тоже

2022-04-18 18:13 UTC, GolovkoStepan commented on .rubocop.yml
> +
тут лишняя пустая строка

2022-04-18 18:14 UTC, GolovkoStepan requested changes
Поправь замечания

2022-04-19 06:46 UTC, AndreyMukhametzyanov commented on spec/models/lesson_spec.rb
> +    let(:user) { build(:user) }
Сделал

2022-04-19 06:46 UTC, AndreyMukhametzyanov commented on spec/models/lesson_spec.rb
> +      expect(lesson).to be_owner(user)
Сделал

2022-04-19 07:47 UTC, AndreyMukhametzyanov commented on spec/controllers/attachments_controller_spec.rb
> +RSpec.describe AttachmentsController, type: :controller do
исправил

2022-04-19 08:28 UTC, AndreyMukhametzyanov commented on .rubocop.yml
> +
Исправил

2022-04-19 08:48 UTC, AndreyMukhametzyanov commented on app/models/course.rb
> +    image_types = %w[image/gif image/jpeg image/pjpeg image/png image/svg+xml
исправил

2022-04-19 10:09 UTC, AndreyMukhametzyanov commented on spec/models/lesson_spec.rb
> +    let(:user) { build(:user) }
сделал

2022-04-19 11:42 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
>    def redirect_with_alert
исправил

2022-04-19 11:42 UTC, AndreyMukhametzyanov commented on app/controllers/courses_controller.rb
>    def redirect_with_alert
Исправил

2022-04-19 11:42 UTC, AndreyMukhametzyanov commented on app/controllers/attachments_controller.rb
> +  def redirect_with_alert(path, msg)
Исправил

2022-04-19 11:48 UTC, GolovkoStepan commented on app/controllers/application_controller.rb
> +  def redirect_with_alert(path, msg)
давай все это в protected засунем

2022-04-19 11:49 UTC, GolovkoStepan commented on spec/controllers/attachments_controller_spec.rb
> +        puts course.cover_picture.id
https://www.youtube.com/watch?v=-Akrtrm4RYs

2022-04-19 11:51 UTC, AndreyMukhametzyanov commented on spec/controllers/attachments_controller_spec.rb
> +        puts course.cover_picture.id
https://www.youtube.com/watch?v=6MQNB0pclyU

2022-04-19 11:52 UTC, GolovkoStepan commented on spec/controllers/attachments_controller_spec.rb
> +        puts course.cover_picture.id
:DD

2022-04-19 11:53 UTC, AndreyMukhametzyanov commented on app/controllers/application_controller.rb
> +  def redirect_with_alert(path, msg)
ok

2022-04-19 11:59 UTC, merged