create_exam
AndreyMukhametzyanov/CoursesApp pull request #26
Opened 2022-04-25 15:06 UTC by AndreyMukhametzyanov

2022-05-14 13:47 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +    answers = examination.current_question.answers.map { |answer| answer.id.to_s }
examination.current_question.answers_ids попробуй

2022-05-14 13:47 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +    user_answers = params[:user_answers]['current_question']
а это перемапить в int

2022-05-14 13:50 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +    correct_answer_counter = 0
не сработает, всегда будет записано 1

2022-05-14 13:51 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +        next_question = examination.exam.questions.where("id > #{current_question.id}")
поставь limit(1) иначе это выражение вернет коллекцию записей

2022-05-14 13:55 UTC, GolovkoStepan commented on app/models/exam.rb
> +  validates :attempts_number, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, allow_blank: true
почему number? как это ваще понять "номер попыток"
переименуй плиз на count

2022-05-14 13:57 UTC, GolovkoStepan commented on app/models/exam.rb
> +  validates :attempts_time, numericality: { only_integer: true, greater_than_or_equal_to: 60 }, allow_blank: true
"время попыток"
attempt_time наверно? лучше все же давать переменным хоть более менее логичные имена в контексте анг языка. Это не придирка, просто читается странно. Больше странного => больше путаницы

2022-05-14 14:01 UTC, GolovkoStepan commented on app/views/exams/_answer_fields.erb
> +    <%= f.input_field :correct_answer, as: :boolean %>
чет тут не так вроде, оно должно быть проще оформлено
f.input :correct_answer, as: :boolean так не получилось?

2022-05-14 14:04 UTC, GolovkoStepan commented on app/views/exams/_form.html.erb
> +            <%= render 'question_fields', :f => question %>
такой синтаксис уже устарел, лучше используй везде типа того f: question
Hash Rocket можно юзать когда у тебя строковый ключ, например 'olololooo' => 'ahahahah'

2022-05-14 14:10 UTC, GolovkoStepan commented on spec/controllers/exams_controller_spec.rb
> +        let(:attempts_time) { 120 }
ты завел этот let, но везде юзаешь захардкоженные значения. Смысл тогда ее заводить?
имею в виду, что нужно использовать ее ниже, а не магическое число

подробнее https://ru.wikipedia.org/wiki/Магическое_число_(программирование)

2022-05-14 14:17 UTC, GolovkoStepan commented on spec/factories/examinations.rb
> +  factory :examination do
тут надо бы добавить все связанные модели, чтобы эта фактори могла создавать эту модель вместе с тем, что еще нужно (exam, course, user и тд)

2022-05-14 14:19 UTC, GolovkoStepan commented on spec/factories/exams.rb
> +  factory :exam do
а тут у нас не будет вопросов, предлагаю добавить trait :with_questions чтобы можно было создать экзамен сразу с вопросами. Подробнее о том, что такое trait можно найти в доке factory_bot

2022-05-14 14:20 UTC, GolovkoStepan commented on spec/factories/questions.rb
> +  factory :question do
а тут можно добавить trait :with_answers

2022-05-15 16:30 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +    answers = examination.current_question.answers.map { |answer| answer.id.to_s }
мне необходимо выбрать все вопросы где correct_answers = true. "examination.current_question.answers_ids" это мне вернет массив айдишников ВСЕХ вопросов. Поэтому делаю так : answers = examination.current_question.answers.where('correct_answer=true').map { |answer| answer.id.to_i }

2022-05-15 16:31 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +    user_answers = params[:user_answers]['current_question']
перемапил откомментил выше

2022-05-15 16:33 UTC, AndreyMukhametzyanov commented on app/models/exam.rb
> +  validates :attempts_number, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, allow_blank: true
изменил

2022-05-15 16:34 UTC, AndreyMukhametzyanov commented on app/models/exam.rb
> +  validates :attempts_time, numericality: { only_integer: true, greater_than_or_equal_to: 60 }, allow_blank: true
исправил

2022-05-15 16:35 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +        next_question = examination.exam.questions.where("id > #{current_question.id}")
исправил

2022-05-15 16:43 UTC, AndreyMukhametzyanov commented on app/views/exams/_answer_fields.erb
> +    <%= f.input_field :correct_answer, as: :boolean %>
исправил. В доке увидел что так было

2022-05-15 16:44 UTC, AndreyMukhametzyanov commented on app/views/exams/_form.html.erb
> +            <%= render 'question_fields', :f => question %>
Понял исправил

2022-05-15 16:46 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +    answers = examination.current_question.answers.map { |answer| answer.id.to_s }
1) я комменчу код, который тут вижу
2) айдищники и так типа int, нет нужды их явмно приводить к int
3) если нужны только айдишники, то используй pluck(:id)

2022-05-15 16:46 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +    user_answers = params[:user_answers]['current_question']
читай выше

2022-05-17 07:23 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +    correct_answer_counter = 0
исправил

2022-06-12 10:53 UTC, GolovkoStepan requested changes
вроде ок, поправь замечания, если рубокоп не пройдет то сделай ограничение выше в его конфиге

2022-06-12 10:53 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +                           correct_answers: correct_answer)
```suggestion
        examination.update(
          current_question: examination.next_question,
          next_question: examination.exam.questions.where('id > ?', current_question.id).first,
          correct_answers: correct_answer
        )
```

2022-06-12 10:53 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +      redirect_to examination_path(examination.id)
при раскладе, когда у нас нет следующего вопроса нету смысла делать редирект на show, можно сразу пойти на course_path

2022-06-12 10:53 UTC, GolovkoStepan commented on app/controllers/exams_controller.rb
> +    @course = Course.find_by(id: params[:course_id])
давай тут тоже колбек забабахаем, по аналогии как я предложил выше

2022-06-12 10:53 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +
лишняя пустая строка

2022-06-12 10:53 UTC, GolovkoStepan commented on app/controllers/exams_controller.rb
> +      @user_attempts = Examination.where(user: current_user, exam: @exam).count
точно ли надо еще раз это из БД тащить?

2022-06-12 10:53 UTC, GolovkoStepan commented on app/views/exams/_form.html.erb
> +
лишняя

2022-06-12 10:53 UTC, GolovkoStepan commented on app/views/exams/show.html.erb
> +<div><%= "#{t('exam.description')}: #{@course.exam.description}" %></div>
не совсем понял смысла оборачивать это в div, если нужны переносы на другую строку - есть параграф

2022-06-12 10:53 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +        <%= link_to "#{t('lessons.lesson_num')} #{i + 1}", course_lesson_path(@course, lesson), class: "list-group-item list-group-item-action my-1 #{css_class}" %>
like

2022-06-12 10:53 UTC, GolovkoStepan commented on spec/controllers/examinations_controller_spec.rb
> +    Exam.create(course: course, title: 'MyExam', description: 'Text', attempts_count: 1, attempt_time: 120,
а че там по фабрикам?

2022-06-12 10:56 UTC, GolovkoStepan commented
ci упало с Your Ruby version is 3.0.2, but your Gemfile specified 3.1.2
поправь конфиг

2022-06-13 10:02 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +    true if percentage_passing >= 80
done

2022-06-13 10:07 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +  def answers_percentage(model)
done

2022-06-13 10:21 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +    examination = Examination.find(params[:id])
done

2022-06-13 10:29 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +    answers = examination.current_question.answers.where(correct_answer: true).pluck(:id)
done

2022-06-13 10:34 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +    user_answers = params[:user_answers].nil? ? [] : params[:user_answers]['current_question'].map(&:to_i)
done

2022-06-13 10:59 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +    if examination.time_remaining <= 0
done

2022-06-13 11:10 UTC, AndreyMukhametzyanov commented on app/javascript/packs/exam_timer.js
> +document.addEventListener("turbolinks:load", function (event) {
done

2022-06-13 11:12 UTC, AndreyMukhametzyanov commented on app/models/exam.rb
> +  def passed?(user)
done

2022-06-13 11:18 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +                           correct_answers: correct_answer)
done

2022-06-13 11:21 UTC, AndreyMukhametzyanov commented on app/controllers/exams_controller.rb
> +    @course = Course.find_by(id: params[:course_id])
done

2022-06-13 11:26 UTC, AndreyMukhametzyanov commented on app/views/exams/_form.html.erb
> +
done

2022-06-13 11:30 UTC, AndreyMukhametzyanov commented on app/views/exams/show.html.erb
> +<div><%= "#{t('exam.description')}: #{@course.exam.description}" %></div>
у параграфа станадратные не настраиваемые отступы между строк. с дивом смотрится лучше но я изменил

2022-06-13 11:33 UTC, AndreyMukhametzyanov commented on app/views/lessons/show.html.erb
> +        <%= link_to "#{t('lessons.lesson_num')} #{i + 1}", course_lesson_path(@course, lesson), class: "list-group-item list-group-item-action my-1 #{css_class}" %>
ty

2022-06-13 11:36 UTC, AndreyMukhametzyanov commented on app/controllers/exams_controller.rb
> +      @user_attempts = Examination.where(user: current_user, exam: @exam).count
done

2022-06-13 11:47 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +        examination.update(correct_answers: correct_answer,
done

2022-06-13 11:47 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +
done

2022-06-13 11:58 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +      redirect_to examination_path(examination.id)
не согласен зачем выкидывать пользователя на курс когда надо показать ему результаты.

2022-06-15 13:09 UTC, GolovkoStepan approved these changes

2022-06-15 13:11 UTC, merged