add feedbacks and tests
AndreyMukhametzyanov/CoursesApp pull request #31
Opened 2022-06-18 16:19 UTC by AndreyMukhametzyanov

2022-06-18 16:50 UTC, GolovkoStepan requested changes
В тестах нет проверки, что фидбеки таки рендерятся на странице курса
Нет возможности отредактировать фитбек, давай сделаем это тоже

2022-06-18 16:50 UTC, GolovkoStepan commented on app/controllers/feedbacks_controller.rb
> +    redirect_to courses_path
а зачем редирект на индекс курсов? наверно надо на страницу курса, к которому фитбек написали?

2022-06-18 16:50 UTC, GolovkoStepan commented on app/controllers/feedbacks_controller.rb
> +    @feedback.save ? flash[:notice] = t('feedbacks.create.success') : flash[:alert] = t('feedbacks.create.error')
у тебя же есть методы, аля redirect_with_alert и тп, чего не юзаешь их?

2022-06-18 16:50 UTC, GolovkoStepan commented on app/views/feedbacks/_form.html.erb
> +  <p><%= f.collection_radio_buttons :grade, [[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5']], :first, :last %></p>
давай лучше комбобокс интовый тут юзать

2022-06-19 19:31 UTC, GolovkoStepan requested changes

2022-06-19 19:31 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +    @feedback = Feedback.find_by(course:@course, user: current_user)
фидбеки следует грузить тут
`@feedbacks = ..........`

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +<%= render partial: 'feedbacks/feedbacks', locals: { resource: @course } %>
надо вывести коллекцию фидбеков вот так вот:
`render @feedbacks`

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +<% end %>
весь этот код нужно заменить на
`render partial: 'feedbacks/form', locals: { course: @course, feedback: @feedback } `

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +<%= render partial: 'feedbacks/feedbacks', locals: { resource: @course } %>
чтобы это работало см. коммент про паршал фидбекс

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/feedbacks/_feedbacks.html.erb
> +<h5 class="my-3"><%= t('feedbacks.all_feedbacks') %></h5>
вместо этого паршла нужен паршл _feedback.html.erb
который включает только код представления одного паршла

```
<div class="card mb-4" style="width: 40rem;">
      <div class="card-header">
        <div class="container">
          <div class="row">
            <div class="col-sm"><%= feedback.user.first_name %></div>
            <div class="col-sm"> Grade: <%= feedback.grade %></div>
            <div class="col-sm" style="padding-left: 30px;padding-right: 0px;">
              <%= feedback.created_at.strftime("%Y.%m.%d %H:%M") %> MSK
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text"><%= feedback.body %></p>
      </div>
    </div>
```

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/feedbacks/_feedbacks.html.erb
> +<h5 class="my-3"><%= t('feedbacks.all_feedbacks') %></h5>
заголовок и проверочку на пустую коллекцию надо перенести в promo

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/feedbacks/_feedbacks.html.erb
> +      <div class="card-body">
боди надо выводить если оно не пустое, а лучше вообще изменить верстку в том случае, когда отзыв содержит только оценку. Думаю можно вместо карточек что-нить другое использовать, поэкспериментируй

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/feedbacks/edit.html.erb
> +<h1><%= t('feedbacks.edit_feedback') %></h1>
это соответственно нам уже не нужно будет

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/feedbacks/edit.html.erb
> +<h1><%= t('feedbacks.edit_feedback') %></h1>
вся эта страница

2022-06-19 19:31 UTC, GolovkoStepan commented on app/controllers/feedbacks_controller.rb
> +  def edit
этот экшен не нужен

2022-06-19 19:31 UTC, GolovkoStepan commented on config/routes.rb
> +    resources :feedbacks, only: %i[create edit update destroy]
эдит не нужен

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/feedbacks/_form.html.erb
> +<%= simple_form_for resource.append(Feedback.new) do |f| %>
это заменить на [course, feedback]

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/feedbacks/_form.html.erb
> +  <%= f.button :submit, t('buttons.create'), class: "btn btn-outline-primary mt-3" %>
тут тернарный оператор с проверкой на persist? и в зависимости от результата выводим нужный текст для кнопки

2022-06-19 19:31 UTC, GolovkoStepan commented on spec/controllers/feedbacks_controller_spec.rb
> +RSpec.describe FeedbacksController, type: :controller do
надо проверить что все ветви кода работают, те когда незаписанный пользователь

2022-06-19 19:31 UTC, GolovkoStepan commented on config/locales/ru.yml
> +    edit_feedback: 'Редактировать отзыв'
это тоже не надо

2022-06-19 19:31 UTC, GolovkoStepan commented on config/locales/ru.yml
> +      error: "Что-то пошло не так"
тк мы не сможем отрендерить ошибки на полях, тут нужна конкретика. Это тоже не пригодится

2022-06-19 19:31 UTC, GolovkoStepan commented on app/controllers/feedbacks_controller.rb
> +        redirect_with_alert(promo_course_path(@course), I18n.t('feedbacks.update.error'))
тут во флеше нужны ошибки модели, иначе не понятно из-за чего не обновилось

2022-06-19 19:31 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +<% end %>
и оно должно выводиться, когда у нас `@course.enrolled_in_course?(current_user) == true`

2022-06-19 19:31 UTC, GolovkoStepan commented on spec/controllers/feedbacks_controller_spec.rb
> +# frozen_string_literal: true
добавить тесты для редактирования

2022-06-19 19:31 UTC, GolovkoStepan commented on spec/controllers/feedbacks_controller_spec.rb
> +# frozen_string_literal: true
и дополнить тест страницы promo курса

2022-06-19 19:45 UTC, GolovkoStepan commented
Еще чекни, может ли автор быть записан на свой курс. Если да, то надо исправить это начиная с модели (сделать валидацию) и заканчивая тестами. В этом пр

2022-06-21 12:55 UTC, AndreyMukhametzyanov commented on app/javascript/packs/application.js
> +//yo
уо

2022-06-22 06:53 UTC, AndreyMukhametzyanov commented on app/controllers/feedbacks_controller.rb
> +    @feedback.save ? flash[:notice] = t('feedbacks.create.success') : flash[:alert] = t('feedbacks.create.error')
исправил

2022-06-22 06:53 UTC, AndreyMukhametzyanov commented on app/controllers/feedbacks_controller.rb
> +    redirect_to courses_path
исправил

2022-06-22 06:54 UTC, AndreyMukhametzyanov commented on app/controllers/feedbacks_controller.rb
> +    if @course.owner?(current_user) || @course.enrolled_in_course?(current_user)
исправил

2022-06-22 07:25 UTC, AndreyMukhametzyanov commented on app/javascript/stylesheets/application.scss
>  trix-editor.form-control {
done

2022-06-22 15:27 UTC, AndreyMukhametzyanov commented on config/routes.rb
> +    resources :feedbacks, only: %i[create edit update destroy]
done

2022-06-23 13:32 UTC, AndreyMukhametzyanov commented on app/controllers/feedbacks_controller.rb
> +        redirect_with_alert(promo_course_path(@course), I18n.t('feedbacks.create.error'))
исправил

2022-06-23 15:43 UTC, AndreyMukhametzyanov commented on app/views/feedbacks/_form.html.erb
> +  <p><%= f.collection_radio_buttons :grade, [[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5']], :first, :last %></p>
done

2022-06-23 15:43 UTC, AndreyMukhametzyanov commented on app/controllers/courses_controller.rb
> +    @feedback = Feedback.find_by(course:@course, user: current_user)
done

2022-06-23 15:45 UTC, AndreyMukhametzyanov commented on app/views/feedbacks/_feedbacks.html.erb
> +<% if Feedback.all.empty? %>
сделал

2022-06-23 16:05 UTC, AndreyMukhametzyanov commented on app/views/feedbacks/_form.html.erb
> +<%= simple_form_for resource.append(Feedback.new) do |f| %>
ок

2022-06-23 16:05 UTC, AndreyMukhametzyanov commented on app/views/feedbacks/_form.html.erb
> +  <%= f.button :submit, t('buttons.create'), class: "btn btn-outline-primary mt-3" %>
сделано

2022-06-24 10:28 UTC, AndreyMukhametzyanov commented on config/locales/ru.yml
> +    edit_feedback: 'Редактировать отзыв'
Ok

2022-06-24 10:28 UTC, AndreyMukhametzyanov commented on config/locales/ru.yml
> +      error: "Что-то пошло не так"
Исправил

2022-06-24 10:29 UTC, AndreyMukhametzyanov commented on app/controllers/feedbacks_controller.rb
> +        redirect_with_alert(promo_course_path(@course), I18n.t('feedbacks.update.error'))
Исправил

2022-06-24 10:59 UTC, GolovkoStepan commented on app/controllers/application_controller.rb
> +  around_action :switch_locale
не знаю, где ты это нагуглил, но можно проще сделать

```
before_action :set_locale

def default_url_options
    I18n.default_locale == I18n.locale ? {} : { locale: I18n.locale }
  end

  private

  def set_locale
    I18n.locale = I18n.locale_available?(params[:locale]) ? params[:locale] : I18n.default_locale
  end
```

2022-06-24 12:02 UTC, AndreyMukhametzyanov commented on app/views/courses/promo.html.erb
> +<% end %>
сделал

2022-06-24 12:09 UTC, AndreyMukhametzyanov commented on app/views/feedbacks/_feedbacks.html.erb
> +      <div class="card-body">
сделал

2022-06-27 16:14 UTC, GolovkoStepan approved these changes

2022-06-27 16:15 UTC, merged