progress_bar_for_lessons
AndreyMukhametzyanov/CoursesApp pull request #37
Opened 2022-07-12 12:47 UTC by AndreyMukhametzyanov

2022-07-14 13:01 UTC, GolovkoStepan requested changes

2022-08-01 16:24 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +    progress = { 'total_lessons' => @course.lessons.count, 'completed_lessons_ids' => [] }
а почему ключи не символы?

2022-08-01 16:25 UTC, GolovkoStepan commented on app/controllers/exams_controller.rb
> +      order&.update(progress: { exam_complete: false })
это зачем?

2022-08-01 16:26 UTC, GolovkoStepan commented on app/controllers/final_projects_controller.rb
> +      order&.update(progress: { project_complete: false })
а это зачем?

2022-08-01 16:56 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +    redirect_with_notice(course_lesson_path(@course, lesson), I18n.t('lessons.lesson_end_msg'))
редирект надо на след лекцию сделать, если она есть. Если нет, то на проект, если он есть. Если нет, то на экзамен, если он есть. Если ниче нету то на страницу промо с флешем "Вы прошли весь курс" (или типа того)

2022-08-01 16:58 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +<% unless @completed_lessons_ids.include?(@lesson.id.to_i) %>
if exclude?

2022-08-01 16:59 UTC, GolovkoStepan commented
Почитай что такое store_accessor, и заюзай это тут

2022-08-02 06:29 UTC, AndreyMukhametzyanov commented on app/controllers/courses_controller.rb
> +    progress = { 'total_lessons' => @course.lessons.count, 'completed_lessons_ids' => [] }
да чтоб дохрена объектов в памяти создалось ))) исправил

2022-08-02 06:30 UTC, AndreyMukhametzyanov commented on app/controllers/exams_controller.rb
> +      order&.update(progress: { exam_complete: false })
эхо войны) исправил

2022-08-02 06:30 UTC, AndreyMukhametzyanov commented on app/controllers/final_projects_controller.rb
> +      order&.update(progress: { project_complete: false })
эхо войны 2) исправил

2022-08-02 06:41 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
> +    end
исправил

2022-08-09 08:54 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
> +    redirect_with_notice(course_lesson_path(@course, lesson), I18n.t('lessons.lesson_end_msg'))
Сделал

2022-08-09 08:54 UTC, AndreyMukhametzyanov commented on app/views/lessons/show.html.erb
> +<% unless @completed_lessons_ids.include?(@lesson.id.to_i) %>
сделал

2022-08-12 07:44 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +      order.save
Давай метод сделаем ордере exam_complete!

2022-08-12 07:46 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +      @percentage = @order.percentage_count
а зачем этот зоопарк переменных? почему бы просто на view не юзать @order.exam_complete и тп?
лишний код как по мне

2022-08-12 07:47 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +      order.save
вот тут тоже давай метод сделаем в ордере, complete_lesson!(lesson_id)

2022-08-12 07:48 UTC, GolovkoStepan commented on app/controllers/replies_controller.rb
> +            order.save
и тут тоже метод project_complete!

2022-08-12 07:53 UTC, GolovkoStepan commented on app/models/order.rb
> +  def total_lessons_count
не оч понятно по названию, что внутри мы должны складывать еще и екз и проект
давай другое имя методу дадим, например total_course_parts

2022-08-12 07:54 UTC, GolovkoStepan commented on app/models/order.rb
> +    total += 1 unless project_complete.nil?
а почему бы не так сделать?
```suggestion
    total += 1 if exam_complete
    total += 1 if project_complete
```
так понятнее выглядит

2022-08-12 07:56 UTC, GolovkoStepan commented on app/models/order.rb
> +    completed_lessons_ids.count * 100 / total_lessons_count
мне кажется это не верно сейчас работать будет, тк не учитываются пройденные проект/экз

2022-08-12 07:57 UTC, GolovkoStepan commented on app/models/order.rb
> +    total += 1 unless project_complete.nil?
или можно progress.key?(:exam_complete)

2022-08-12 08:00 UTC, GolovkoStepan commented on app/controllers/exams_controller.rb
> +                                              percentage_passing: 100).first
можно заменить where на find_by и убрать в конце first, тоже самое будет по идее

2022-08-12 08:02 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +<% if @order && !@course.owner?(current_user) %>
а откуда у автора курса может быть ордер на свой же курс?

2022-08-12 08:04 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +      <%= link_to "#{t('exam.pass_exam')}", course_exam_path(@course), class: "list-group-item list-group-item-#{css_complete} my-1" %>
тут тоже везде проверки на owner, не понимаю зачем они

2022-08-12 08:13 UTC, GolovkoStepan commented on spec/factories/orders.rb
> +      { total_lessons: course.lessons.count,
такое точно работает?

2022-08-12 08:16 UTC, GolovkoStepan requested changes
1) я не нашел кода, который добавит в прогресс complete_exam/complete_project false для всех ордеров курса, которому создали проект или екз и тесты на это
2) мне кажется, что расчет процента прохождения сейчас неверный, тк мы берем только пройденные лекции, а делим это уже на число лекций + екз + проект если они есть.

2022-08-12 08:20 UTC, GolovkoStepan commented on spec/models/order_spec.rb
> +  describe 'percentage count' do
надо проверять 2 случая
1) тока лекции
2) есть лекции и все остальное (экз/проект)

2022-08-12 08:23 UTC, GolovkoStepan commented on spec/models/order_spec.rb
> +                              exam_complete: false })
построив такой хеш ты также должен создать для курса экз и курс, если их у него нету, в хеше не должно быть ключей project_complete и exam_complete

2022-08-12 08:30 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +  def build_progress_hash
давай унесем этот метод в ордер, работать он должен, соответственно тогда, когда есть курс
те или сбилдить хеш или пустой хеш

можно сделать, чтобы он менял изменяемый объект и на основе этого сделать колбек before_create

2022-08-12 10:39 UTC, AndreyMukhametzyanov commented on app/controllers/examinations_controller.rb
> +      order.save
Исправил

2022-08-12 10:41 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
> +      order.save
Исправил

2022-08-12 10:45 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
> +      @percentage = @order.percentage_count
Исправил

2022-08-12 10:47 UTC, AndreyMukhametzyanov commented on app/controllers/replies_controller.rb
> +            order.save
исправил

2022-08-12 10:51 UTC, AndreyMukhametzyanov commented on app/models/order.rb
> +  def total_lessons_count
исправил

2022-08-12 10:52 UTC, AndreyMukhametzyanov commented on app/models/order.rb
> +    total += 1 unless project_complete.nil?
исправил

2022-08-12 12:35 UTC, AndreyMukhametzyanov commented on app/controllers/exams_controller.rb
> +                                              percentage_passing: 100).first
да проверил в консольке. Исправил

2022-08-12 12:41 UTC, AndreyMukhametzyanov commented on spec/factories/orders.rb
> +      { total_lessons: course.lessons.count,
нет не работает удалил исправил

2022-08-12 12:46 UTC, AndreyMukhametzyanov commented on spec/models/order_spec.rb
> +                              exam_complete: false })
понял в данном контексте они были лишние.

2022-08-13 11:55 UTC, AndreyMukhametzyanov commented on app/models/order.rb
> +    completed_lessons_ids.count * 100 / total_lessons_count
Исправил

2022-08-13 16:17 UTC, AndreyMukhametzyanov commented on app/controllers/courses_controller.rb
> +  def build_progress_hash
исправил

2022-08-13 16:28 UTC, AndreyMukhametzyanov commented on spec/models/order_spec.rb
> +  describe 'percentage count' do
Сделал

2022-08-15 08:57 UTC, GolovkoStepan commented on app/models/course.rb
> +  end
Подумай какая тут проблема

2022-08-15 09:16 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +        <% css_complete = !@course.owner?(current_user) && @order.lesson_complete?(lesson.id) ? "success" : "action" %>
@order&.lesson_complete?(lesson.id)

2022-08-15 09:17 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +      <% css_complete = !@course.owner?(current_user) && @course.final_project && @order.project_complete ? "success" : "action" %>
` @order&.project_complete`

зачем тут `@course.final_project` которая всегда будет true, не понимаю. На строку выше эта же самая проверка.

2022-08-15 09:23 UTC, GolovkoStepan commented
Если у нас например 3 лекции, я вот только записался. Перехожу на 2 лекцию и нажимаю кнопку "завершить". Она отмечается как "завершенная". Далее, будет редирект на 3 лекцию. Потом я перехожу на первую и нажимаю кнопку "завершить". Она отмечается как завершенная и будет редирект на 2 лекцию. Должен быть на третью.

2022-08-15 09:33 UTC, GolovkoStepan commented
Давай изменим текст у кнопки "Продолжить обучение", когда мы под автором зашли. Пусть будет "Контент курса" или что-то типа того.

2022-08-18 10:29 UTC, AndreyMukhametzyanov commented on app/views/lessons/show.html.erb
> +        <% css_complete = !@course.owner?(current_user) && @order.lesson_complete?(lesson.id) ? "success" : "action" %>
исправил

2022-08-18 10:29 UTC, AndreyMukhametzyanov commented on app/views/lessons/show.html.erb
> +      <% css_complete = !@course.owner?(current_user) && @course.final_project && @order.project_complete ? "success" : "action" %>
исправил

2022-08-18 10:29 UTC, AndreyMukhametzyanov commented on app/views/lessons/show.html.erb
> +      <% css_complete = !@course.owner?(current_user) && @course.exam && @order.exam_complete ? "success" : "action" %>
исправил

2022-08-18 13:44 UTC, AndreyMukhametzyanov commented on app/models/course.rb
> +  end
исправил

2022-08-22 14:26 UTC, GolovkoStepan commented on app/controllers/examinations_controller.rb
> +      order.exam_complete!
https://clck.ru/tn8n2

2022-08-22 14:29 UTC, GolovkoStepan commented on spec/controllers/examinations_controller_spec.rb
> +  let(:create_order) do
а почему бы не сделать let!(: create_order) и не надо будет это все в before писать везде

2022-08-22 14:43 UTC, GolovkoStepan commented
Необходимо понять причину моего столь резкого комментария, а также написать нормальные тесты для в examinations_controller_spec

2022-08-22 16:19 UTC, GolovkoStepan approved these changes

2022-08-22 16:20 UTC, merged