LIKOMETR
AndreyMukhametzyanov/CoursesApp pull request #45
Opened 2022-11-15 13:11 UTC by AndreyMukhametzyanov

2022-11-15 13:37 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +  def get_information(kind)
Имя метода не отражает его сути

2022-11-15 13:39 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +        kind == 'like' ? @user_vote.like! : @user_vote.dislike!
update(kind: kind)

2022-11-15 13:40 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +      :lesson, :title, :content, :youtube_video_id, :order_factor, :likes, :dislikes,
Зачем это было добавлено?

2022-11-15 13:41 UTC, GolovkoStepan commented on app/models/vote.rb
> +  enum kind: { not_set: 0, like: 1, dislike: 2 }
Нужна валидация на наличие значения при создании. Либо лайк либо диз, другого не дано.

2022-11-28 17:45 UTC, GolovkoStepan commented on app/javascript/packs/vote.js
> +
Уже вот тут можно понять, стоит ли дальше что-то делать

2022-11-28 17:57 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +    @courses = courses.map(&:votes).sort_by { |hsh| hsh[:likes] }.reverse!
```
Course
  .left_joins(lessons: :votes)
  .select(
    'courses.*',
    "SUM(case when votes.kind = 'like' then 1 else 0 end) as likes_count",
    "SUM(case when votes.kind = 'dislike' then 1 else 0 end) as dislikes_count"
  )
  .group('courses.id')
  .order('likes_count DESC')
```

2022-11-28 17:59 UTC, GolovkoStepan commented on app/javascript/packs/vote.js
> +            console.log(xhr.response)
всякие выводы в консоль уже можно убирать, раз ты это допилил

2022-11-28 18:00 UTC, GolovkoStepan requested changes
Нет теста индекса курсов

2022-11-29 08:54 UTC, AndreyMukhametzyanov commented on app/javascript/packs/vote.js
> +
исправил

2022-11-29 08:55 UTC, AndreyMukhametzyanov commented on app/javascript/packs/vote.js
> +            console.log(xhr.response)
исправил

2022-11-29 08:55 UTC, AndreyMukhametzyanov commented on app/models/vote.rb
> +  enum kind: { not_set: 0, like: 1, dislike: 2 }
исправил

2022-11-29 13:35 UTC, AndreyMukhametzyanov commented on db/migrate/20221114122633_create_votes.rb
> +      t.integer :kind
исправил

2022-11-30 14:09 UTC, AndreyMukhametzyanov commented on app/controllers/courses_controller.rb
> +    @courses = courses.map(&:votes).sort_by { |hsh| hsh[:likes] }.reverse!
гениально

2022-12-01 16:49 UTC, merged