Controllers
AndreyMukhametzyanov/CoursesApp pull request #8
Opened 2022-01-24 12:09 UTC by AndreyMukhametzyanov

2022-01-25 12:46 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +    @course = Course.find_by_id(params[:id])
Course.find(params[:id]) тоже самое

2022-01-25 12:47 UTC, GolovkoStepan commented on app/views/courses/index.html.erb
> +<h1 class="text-center">Платформа для онлайн курсов</h1>
настрой среду на 2 пробела в качестве отступа, а то это все ползет вправо, не оч смотрится

2022-01-25 12:48 UTC, GolovkoStepan commented on app/views/courses/show.html.erb
> +<div class="row">
вот тут норм, аккуратно выглядит

2022-01-25 12:48 UTC, GolovkoStepan commented on app/views/courses/show.html.erb
> +</div>
не забывай пустую строку в конце файла, чтобы не было тут этого символа

2022-01-25 12:50 UTC, GolovkoStepan commented on app/views/devise/registrations/edit.html.erb
> +<h2><%= t('edit.edit') %></h2>
вроде можно просто .edit, yml заресолвится по пути до этого файла. Но эт не точно, надо проверить

2022-01-26 16:54 UTC, GolovkoStepan requested changes

2022-01-26 16:54 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +    @course = Course.find_by_id(params[:id])
почему ты пишешь find_by_id если можно просто find? это тоже самое

2022-01-26 16:54 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +    @lesson = Lesson.first.id
не правильно. нам нужна первая лекция ЭТОГО курса, а не просто первая лекция любого курса

2022-01-26 16:54 UTC, GolovkoStepan commented on app/views/courses/index.html.erb
>  </div>
я просил сократить отступы ДО 2х ПРОБЕЛОВ, сейчас хуже чем было

2022-01-26 16:54 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +<a href="javascript:history.back()">Назад</a>
лучше не использовать это, надо сделать переход обратно на промо курса точной ссылкой

2022-01-26 17:10 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +<a href="javascript:history.back()">Назад</a>
точнее это вообще надо выпилить, тк есть бредкрамбы

2022-01-26 17:11 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +				<a href="#" class="list-group-item list-group-item-action">Лекция 2</a>
а тут надо вывести все ссылки на лекции курса в цикле

2022-01-26 17:25 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +        <li class="breadcrumb-item active" aria-current="page"><%= link_to "#{@course.name}", course_path %></li>
зачем нужна ссылка на текущую страницу? нужно убрать ссылку и сделать просто текст

2022-01-26 17:25 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +<a href="javascript:history.back()">Назад</a>
удалить

2022-01-26 17:27 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +				<li class="breadcrumb-item active" aria-current="page"><%= link_to "#{@course.name}", course_path %></li>
вот сюда надо добавить еще текущую страницу (текстом, не ссылкой)

2022-01-26 17:27 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +				<li class="breadcrumb-item active" aria-current="page"><%= link_to "#{@course.name}", course_path %></li>
+ эта ссылка не работает, исправить

2022-01-26 17:34 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +  <%= link_to 'Start learning', start_course_path, class: 'btn btn-outline-primary' %>
эта кнопка не должна быть доступна, если у курса нет лекций

2022-03-16 19:26 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +    # render plain: course_params
Удалить

2022-03-16 19:29 UTC, GolovkoStepan commented on app/models/course.rb
> +    correct_link = video_link.split('=').first
2 раза split, можно вот так
```suggestion
    correct_link, id  = video_link.split('=').first
```

2022-03-16 19:31 UTC, GolovkoStepan commented on app/models/lesson.rb
> +  scope :order_factor, -> { order(order_factor: :ASC) }
Вообще, у тебя поле у модели и этот скоуп одинаково называются. Можно спутаться. Надо переименовать его, мб order_by_factor

2022-03-16 19:34 UTC, GolovkoStepan commented on app/views/courses/edit.html.erb
> +<%= simple_form_for @course do |f| %>
Формы идентичные с new. Нужно оформить как partial. 
https://human-se.github.io/rails-demos-n-deets-2021/demos/form-partials/

2022-03-16 19:35 UTC, GolovkoStepan commented on app/views/courses/index.html.erb
> +<h1 class="text-center my-4"><%= t('courses.index.head') %></h1>
Наведи тут порядок плиз

2022-03-16 19:35 UTC, GolovkoStepan commented on app/views/courses/new.html.erb
> +<h1>Создать курс</h1>
Вынести в partial

2022-03-16 19:36 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +        <li class="breadcrumb-item"><%= link_to t('courses.breadcrumb.home'), root_path %></li>
беды с отсупами

2022-03-16 19:37 UTC, GolovkoStepan commented on app/views/lessons/edit.html.erb
> +<%= simple_form_for [@course, @lesson] do |f| %>
беды с отступами

2022-03-16 19:37 UTC, GolovkoStepan commented on app/views/lessons/edit.html.erb
> +<% end %>
нет пустой строки в конце файла

2022-03-16 19:38 UTC, GolovkoStepan commented on app/views/lessons/new.html.erb
> +<%= simple_form_for [@course, @lesson] do |f| %>
идентичная форма с edit, вынести в partial

2022-03-16 19:39 UTC, GolovkoStepan commented on db/migrate/20220129104249_add_order_factor_to_lesson.rb
> +
пустая строка тут лишняя

2022-03-16 19:41 UTC, GolovkoStepan commented on spec/models/course_spec.rb
> +      User.new(id: 1, first_name: 'User', last_name: 'Userovich', date_of_birth: '01.01.2002', email: 'test@test.com')
для этого есть factory bot, переделать на build

2022-03-16 19:41 UTC, GolovkoStepan commented on spec/models/course_spec.rb
> +    let!(:my_course) { Course.new(user: my_user, name: 'Dota2', description: 'Dota2', level: 1) }
и тут

2022-03-16 19:42 UTC, GolovkoStepan commented
Написать тесты

2022-03-16 19:44 UTC, GolovkoStepan commented
Добавить пустую строку в конец каждого файла, можно рубимайн настроить на это

2022-03-17 18:36 UTC, GolovkoStepan commented on app/views/courses/edit.html.erb
> +<%= render "forms/course_form" %>
Почти верно. Но нужно сделать в папке course, просто _form.html.erb. Те сделать так, как написано в статье, которую я тут приложил.

2022-03-17 18:39 UTC, GolovkoStepan commented on app/views/forms/_lesson_form.html.erb
> +  <div class="btn btn-outline-primary mt-3">
а зачем ты эту кнопку оборачиваешь в бутстаповские классы?
назначь эти классы ей самой и не нужен будет этот div

2022-03-17 18:39 UTC, GolovkoStepan commented on app/views/lessons/edit.html.erb
> +<%= render "forms/lesson_form" %>
тоже самое, надо в папке lessons сделать _form.html.erb

2022-03-17 18:41 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +      expect(response).to render_template('index')
тут еще надо проверить, что у нас нужные переменные имеют нужные данные
загугли assigns

2022-03-17 18:43 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +  <%= link_to 'Start learning', start_course_path, class: 'btn btn-outline-primary' %>
не вижу исправления этого замечания

2022-03-17 19:55 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +		<%= link_to t('courses.promo.edit_course'), edit_course_path(@course), class: 'btn btn-outline-primary' %>
Кнопка изменения доступна только автору

2022-03-17 20:12 UTC, GolovkoStepan commented on app/views/courses/index.html.erb
> +<h1 class="text-center my-4"><%= t('courses.index.head') %></h1>
Готово!

2022-03-17 20:12 UTC, GolovkoStepan commented on app/views/courses/index.html.erb
> +<h1 class="text-center my-4"><%= t('courses.index.head') %></h1>
Спасибо!

2022-03-18 07:27 UTC, AndreyMukhametzyanov commented on app/views/courses/show.html.erb
> +<div class="row">
Спасибо

2022-03-18 07:27 UTC, AndreyMukhametzyanov commented on app/views/lessons/show.html.erb
> +<a href="javascript:history.back()">Назад</a>
убрал

2022-03-18 07:28 UTC, AndreyMukhametzyanov commented on app/views/lessons/edit.html.erb
> +<%= simple_form_for [@course, @lesson] do |f| %>
исправил

2022-03-18 07:29 UTC, AndreyMukhametzyanov commented on app/views/courses/promo.html.erb
> +        <li class="breadcrumb-item"><%= link_to t('courses.breadcrumb.home'), root_path %></li>
исправил

2022-03-18 07:42 UTC, AndreyMukhametzyanov commented on app/views/courses/edit.html.erb
> +<%= render "forms/course_form" %>
Исправил

2022-03-18 11:52 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +      expect(response).to render_template('index')
Сделал

2022-03-18 19:02 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +  end
тут лучше сделать как инлайн блок, когда у тебя всего одна строка
```suggestion
  before { sign_in user }
```
исправление по желанию

2022-03-18 19:13 UTC, GolovkoStepan commented on app/models/course.rb
> +    video_link.nil? ? nil : self[:youtube_video_id] = video_link.split('=').last
ни где не видел такого подхода, это можно сделать проще, тк у модели есть уже есть setter для этого столбца
```suggestion
    video_link.nil? ? nil : self.youtube_video_id = video_link.split('=').last
```

да и вообще, тут тернарный оператор не нужен, лучше сделать так
```suggestion
    self.youtube_video_id = video_link.split('=').last if video_link
```

2022-03-18 19:17 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +      :new
это явно не будет работать так, как ты планируешь

2022-03-18 19:23 UTC, GolovkoStepan commented on app/views/courses/_form.html.erb
> +  <%= f.button :submit, t('buttons.confirm'), class: "btn btn-outline-primary mt-3" %>
надо сделать чтобы текст у кнопки был разный: для создания - создать, для изменения - сохранить
у лекций тоже самое

2022-03-18 19:32 UTC, GolovkoStepan commented on app/models/course.rb
> +    correct_link == correct ? id : errors.add(:video_link, 'this link is not from YouTube hosting')
эту ошибку надо локализировать

2022-03-18 19:43 UTC, GolovkoStepan commented on app/views/courses/promo.html.erb
> +		<%= link_to t('courses.promo.edit_course'), edit_course_path(@course), class: 'btn btn-outline-primary' %>
тоже самое касается лекций (создание и изменеие лекций делает автор курса), в добавок к этому:
1) страницы не должны быть доступны, те например при ручном вводе URI создания лекции должен быть редирект с флешем, что доступ сюда имеет только автор
2) все экшены контроллера должны иметь проверку, те в том числе экшены create и update. На случай, когда можно подделать запрос от браузера.

те проверку делаем для всех экшенов new edit create update для лекций и edit update для курсов

2022-03-19 08:08 UTC, AndreyMukhametzyanov commented on app/views/lessons/new.html.erb
> +<%= simple_form_for [@course, @lesson] do |f| %>
исправил

2022-03-19 08:08 UTC, AndreyMukhametzyanov commented on spec/models/course_spec.rb
> +      User.new(id: 1, first_name: 'User', last_name: 'Userovich', date_of_birth: '01.01.2002', email: 'test@test.com')
исправил

2022-03-19 08:11 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +  end
исправил

2022-03-19 08:12 UTC, AndreyMukhametzyanov commented on app/models/course.rb
> +    video_link.nil? ? nil : self[:youtube_video_id] = video_link.split('=').last
я хочу оставить так для понимания

2022-03-19 08:17 UTC, GolovkoStepan commented on app/models/course.rb
> +    video_link.nil? ? nil : self[:youtube_video_id] = video_link.split('=').last
"я пишу так потому что мне так понятнее" - какой смысл мне тогда проводить ревью?

2022-03-19 08:19 UTC, AndreyMukhametzyanov commented on app/views/lessons/show.html.erb
> +<div class="row">
исправил

2022-03-19 08:25 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
> +      :new
исправил

2022-03-19 09:07 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +		<H5><%= t('lessons.lesson_list') %></H5>
Что еще за H5? У нас не химия, имена тегов в нижнем регистре пишут

2022-03-19 10:54 UTC, AndreyMukhametzyanov commented on app/views/courses/_form.html.erb
> +  <%= f.button :submit, t('buttons.confirm'), class: "btn btn-outline-primary mt-3" %>
сделано

2022-03-19 12:51 UTC, AndreyMukhametzyanov commented on app/views/lessons/show.html.erb
> +		<H5><%= t('lessons.lesson_list') %></H5>
исправлено

2022-03-19 13:25 UTC, GolovkoStepan commented on app/views/courses/_form.html.erb
> +<% end %>
Чет опять 25, рубимайн не получилось настроить?

2022-03-19 13:26 UTC, GolovkoStepan commented on app/views/lessons/show.html.erb
> +<div class="row">
Не вижу

2022-03-19 18:06 UTC, AndreyMukhametzyanov commented on app/models/course.rb
> +    correct_link == correct ? id : errors.add(:video_link, 'this link is not from YouTube hosting')
Исправил

2022-03-21 07:52 UTC, AndreyMukhametzyanov commented on app/views/courses/_form.html.erb
> +<% end %>
исправил

2022-03-22 06:49 UTC, AndreyMukhametzyanov commented on app/models/course.rb
> +    video_link.nil? ? nil : self[:youtube_video_id] = video_link.split('=').last
исправил

2022-03-22 06:49 UTC, AndreyMukhametzyanov commented on app/views/lessons/show.html.erb
> +<div class="row">
настроил

2022-03-22 06:56 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +        post :create, params: { course: { user_id: user.id, name: 'Course', video_link: 'asdsa',
Так, а почему ты тут передаешь в параметрах user_id?
Во первых, это породит ворнинг unpermited parameter user_id, тк у тебя оно не прописано в permit_params
Во вторых, мы можем прислать сюда любой айди пользователя, и если бы у нас привязка была бы именно так реализована, то можно было бы создавать курсы другим пользователям - это грубейшее нарушение безопасности.

Удалить это

2022-03-23 05:59 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +    let!(:course) { create :course, id: 1, user: user }
тут id: 1 зачем? удалить

2022-03-23 20:21 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +    redirect_to courses_path
вижу, что оно дублируется у тебя. Сделай приватный метод для этого

2022-03-23 20:23 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +      @lesson = Lesson.new
не совсем верно, надо сбилдить лекцию у найденного курса

2022-03-23 20:24 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +      redirect_to promo_course_path(@course)
тоже вынести в приватный метод

2022-03-23 20:25 UTC, GolovkoStepan commented on app/views/courses/_form.html.erb
> +
лишние пустые строки лучше не делать

2022-03-23 20:30 UTC, GolovkoStepan commented on app/views/lessons/_form.html.erb
> +    <%= f.input :order_factor, collection: 1..@course.lessons.count %>
подумай над тем, когда у нас 1 лекция уже есть, и хотим создать вторую. Что тут не так?

2022-03-23 20:30 UTC, GolovkoStepan commented on app/views/lessons/_form.html.erb
> +  <% if @lesson.new_record? %>
лучше сделать с помощью тернарного оператора

2022-03-23 20:35 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +        expect(Course.last.name).to eq(name)
а что мешает закешировать этот запрос?
`course = Course.last
expect(course.name).to eq(name)
........
`
1 запрос VS n запросов всегда побеждает

2022-03-23 20:37 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +    end
можно оформить как инлайнл блок

2022-03-23 20:38 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +      # откуда взялась точка?
course_lessons_path это что за маршрут? course_lesson_path а это?
В чем их отличия?

2022-03-24 06:26 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +        post :create, params: { course: { user_id: user.id, name: 'Course', video_link: 'asdsa',
Исправил

2022-03-24 06:27 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +    let!(:course) { create :course, id: 1, user: user }
исправил

2022-03-24 06:30 UTC, AndreyMukhametzyanov commented on app/controllers/courses_controller.rb
> +    redirect_to courses_path
исправил

2022-03-24 08:31 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
> +      @lesson = Lesson.new
Исправил

2022-03-24 08:34 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
> +      redirect_to promo_course_path(@course)
исправил

2022-03-24 08:34 UTC, AndreyMukhametzyanov commented on app/views/courses/_form.html.erb
> +
исправил

2022-03-24 08:42 UTC, AndreyMukhametzyanov commented on app/views/lessons/_form.html.erb
> +    <%= f.input :order_factor, collection: 1..@course.lessons.count %>
убрал индекс уникальности

2022-03-24 09:39 UTC, AndreyMukhametzyanov commented on app/views/lessons/_form.html.erb
> +  <% if @lesson.new_record? %>
исправил

2022-03-24 09:50 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +        expect(Course.last.name).to eq(name)
исправил

2022-03-24 09:51 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +    end
исправил

2022-03-24 10:43 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +      # откуда взялась точка?
в то что course_lesson_path это путь до конкретной лекции до экшена show а course_lessons это вообще для метода create

2022-03-24 10:43 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +      # откуда взялась точка?
Исправил

2022-03-24 10:44 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +      # откуда взялась точка?
> в то что course_lesson_path это путь до конкретной лекции до экшена show а course_lessons это вообще для экшена create

2022-03-27 05:08 UTC, GolovkoStepan commented on app/controllers/courses_controller.rb
> +    edit_error
Ну а смысл менять шило на мыло? Переименуй этот метод и добавь туда  redirect_to courses_path
Тогда дублирования не будет

2022-03-27 05:08 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +      auth_alert
Тоже самое

2022-03-27 05:11 UTC, GolovkoStepan commented on config/application.rb
>      config.autoload_paths += Dir.glob("#{config.root}/app/interactions/*")
пути прописаны, папок нет. Зачем они? Удалить лишнее

2022-03-27 05:11 UTC, GolovkoStepan commented on config/locales/en.yml
> +
1 пустая строка в конце каждого файла

2022-03-27 05:12 UTC, GolovkoStepan commented on config/locales/ru.yml
> +
тоже самое

2022-03-27 05:12 UTC, GolovkoStepan commented on config/locales/simple_form.ru.yml
> +
лишние пустые строки

2022-03-27 05:12 UTC, GolovkoStepan commented on config/locales/simple_form.ru.yml
> +
и тут

2022-03-27 05:12 UTC, GolovkoStepan commented on config/locales/simple_form.ru.yml
> +        age: 'Выберите свой возраст'
нет пустой строки в конце

2022-03-27 05:17 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +        post :create, params: { course: { user: user, name: 'Course', video_link: '',
Я уже писал тебе про то, что user_id тут не нужен, ты изменил это и теперь шлешь в параметрах строковое представление объекта. Вопрос "зачем" так и остался без ответа. Удалить это, прочитать еще раз то, что я писал по этому поводу. Если все еще не понятно - в телегу

2022-03-27 05:18 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +        post :create, params: { course: { user: user, name: 'Course', video_link: 'asdsa',
тут тоже самое

2022-03-27 05:19 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +        expect(Course.last).not_to be_a_new(Course)
лучше напиши expect(Course.count).to eq(0)
более понятно будет

2022-03-27 05:22 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +    it 'should returns correct renders for #start' do
should returns correct renders for #start
тут что-то рендерится? вижу тут проверку редиректа. Исправить название

2022-03-27 05:23 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +  describe '#start' do
Добавить тесты когда нет лекций у курса

2022-03-27 05:25 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +  describe '#update' do
не все тесты написаны, надо
1) когда все ок
2) когда ты не овнер курса
3) когда параметры кривые

2022-03-27 05:26 UTC, GolovkoStepan commented on spec/controllers/lessons_controller_spec.rb
> +  describe '#new' do
тест не полный, добавить тесты

2022-03-27 05:27 UTC, GolovkoStepan commented on spec/controllers/lessons_controller_spec.rb
> +  describe '#create' do
тоже самое что и с курсами, добавить тесты

2022-03-27 05:28 UTC, GolovkoStepan commented on spec/controllers/lessons_controller_spec.rb
> +  describe '#edit' do
и тут тоже

2022-03-27 05:28 UTC, GolovkoStepan commented on spec/controllers/lessons_controller_spec.rb
> +  describe '#update' do
ну и тут

2022-03-27 05:29 UTC, GolovkoStepan commented on spec/factories/lessons.rb
> +    title { 'Lesson' }
сделай как у курса через sequence

2022-03-27 05:31 UTC, GolovkoStepan commented on spec/models/course_spec.rb
> +        my_course.save
Всю вот такую подготовительную работу давай вынесем в before. В it будут только проверки expect

2022-03-27 05:31 UTC, GolovkoStepan commented on spec/models/course_spec.rb
> +        my_course.save
Нужно сделать везде

2022-03-27 05:32 UTC, GolovkoStepan commented
Починить CI

2022-03-28 06:51 UTC, AndreyMukhametzyanov commented on app/controllers/courses_controller.rb
> +    edit_error
Исправил

2022-03-28 06:51 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
> +      auth_alert
Исправил

2022-03-28 06:52 UTC, AndreyMukhametzyanov commented on config/application.rb
>      config.autoload_paths += Dir.glob("#{config.root}/app/interactions/*")
Исправил

2022-03-28 06:54 UTC, AndreyMukhametzyanov commented on config/locales/ru.yml
> +
Исправил

2022-03-28 06:54 UTC, AndreyMukhametzyanov commented on config/locales/en.yml
> +
Исправил

2022-03-28 06:57 UTC, AndreyMukhametzyanov commented on config/locales/simple_form.ru.yml
> +
Исправил

2022-03-28 06:58 UTC, AndreyMukhametzyanov commented on config/locales/simple_form.ru.yml
> +
исправил

2022-03-28 06:59 UTC, AndreyMukhametzyanov commented on config/locales/simple_form.ru.yml
> +        age: 'Выберите свой возраст'
исправил

2022-03-28 07:04 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +        expect(Course.last).not_to be_a_new(Course)
Исправил

2022-03-28 07:10 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +    it 'should returns correct renders for #start' do
исправил

2022-03-28 07:54 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +  describe '#start' do
Исправил

2022-03-28 11:30 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +  describe '#update' do
исправил

2022-03-28 11:49 UTC, AndreyMukhametzyanov commented on spec/factories/lessons.rb
> +    title { 'Lesson' }
исправил

2022-03-28 12:53 UTC, AndreyMukhametzyanov commented on spec/models/course_spec.rb
> +        my_course.save
Сделал

2022-03-29 06:28 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +    it 'should returns correct renders for #edit' do
еще тест

2022-03-29 07:43 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +    it 'should returns correct renders for #edit' do
добавил

2022-03-29 16:29 UTC, AndreyMukhametzyanov commented on spec/controllers/lessons_controller_spec.rb
> +  describe '#update' do
исправил

2022-03-29 16:29 UTC, AndreyMukhametzyanov commented on spec/controllers/lessons_controller_spec.rb
> +  describe '#create' do
исправил

2022-03-29 16:29 UTC, AndreyMukhametzyanov commented on spec/controllers/lessons_controller_spec.rb
> +  describe '#new' do
исправил

2022-03-29 17:38 UTC, GolovkoStepan commented on app/controllers/lessons_controller.rb
> +  def auth_alert
давай одинаково назовем redirect_with_alert

2022-03-29 17:39 UTC, GolovkoStepan commented on config/locales/ru.yml
> +
прибери все файлы от такого

2022-03-29 17:41 UTC, GolovkoStepan commented on spec/controllers/courses_controller_spec.rb
> +      let(:user2) { create :user }
лучше не называть так, можно another_user

2022-03-29 17:50 UTC, AndreyMukhametzyanov commented on spec/controllers/courses_controller_spec.rb
> +      let(:user2) { create :user }
исправил

2022-03-29 17:59 UTC, AndreyMukhametzyanov commented on app/controllers/lessons_controller.rb
> +  def auth_alert
исправил

2022-03-30 06:25 UTC, AndreyMukhametzyanov commented on config/locales/ru.yml
> +
исправил

2022-03-30 06:26 UTC, merged